### ISSUE TITLE
Population's best fitness may worsen from one generation to the next

### ISSUE THREAD

**Issue by rcnlee** [abeschneider/GrammaticalEvolution#6]
At GrammaticalEvolution.jl line 95:
`new_population = PopulationType(top_num, genome_size)`
The top performers are replaced by a random population.  The rest are filled with offspring.
This leads to the best performer potentially being discarded resulting in a worsening in the population's best fitness.  Is this intentional? What is the rationale?

Thanks!

**Comment by abeschneider** [comment]
Good find, that is indeed a mistake. The issue is that `PopulationType` doesn't have a constructor to take `top_performers`. It should read:

```
new_population = PopulationType(top_performers, genome_size)
```

and then something like (completely untested) in ExamplePopulation.jl:

```
function ExamplePopulation(individuals::Array{ExampleIndividual, 1}, genome_size::Int64)
    return new(copy(individuals))
end
```

I'll try to commit the fix later today.

**Comment by abeschneider** [comment]
Sorry, it took longer to get around to looking at the code than expected. It should work as expected now. Let me know if you encounter any other issues.
