### ISSUE TITLE
Generations take longer and longer to complete

### ISSUE THREAD

**Issue by rcnlee** [abeschneider/GrammaticalEvolution#7]
Each generation seems to take longer and longer to complete.  For example, in the ant.jl example, the first generation takes around 1 second to complete, but by the time it gets to around generation 30, it takes 4-5 seconds to complete.  By the time it gets to 100ish, it's barely moving.  Anyone else seeing this?

Thanks!

**Comment by abeschneider** [comment]
I've just tried it out with Julia 0.4.2 on a Macbook Pro, and it seems to take ~5secs per generation both around generation 5 as well as generation 100. What version of Julia are you using?

It sounds potentially like a data structure that isn't reset or truncated every generation (e.g. the population). One possible reason I don't see this behavior could be memory related. How much memory do you have on your computer?

**Comment by rcnlee** [comment]
Hmm... I just did a test using a fresh pull of master and it's nowhere near as pronounced as what I was seeing before.  I was using an older version and added some code changes of my own.  On the fresh pull, I see 5 secs/gen in the first 50, getting to 10 secs/gen by 100, then stabilizing around 20 secs/gen afterwards.  I think this may just be because of increasing code length.  I'll close and try to hunt it down. Thanks for the help!
